In [1]:
import torch


In [12]:
t0 = torch.linspace(0, 35, steps=36)
t0

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35.])

In [13]:
input = t0.reshape(1, 4, 3, 3)
input

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.]],

         [[ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]],

         [[18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.]],

         [[27., 28., 29.],
          [30., 31., 32.],
          [33., 34., 35.]]]])

In [9]:
pixel_shuffle = torch.nn.PixelShuffle(2)

In [14]:
pixel_shuffle(input)

tensor([[[[ 0.,  9.,  1., 10.,  2., 11.],
          [18., 27., 19., 28., 20., 29.],
          [ 3., 12.,  4., 13.,  5., 14.],
          [21., 30., 22., 31., 23., 32.],
          [ 6., 15.,  7., 16.,  8., 17.],
          [24., 33., 25., 34., 26., 35.]]]])

Pixel Shuffle Layer will not change the value, but just change the position of element.